### ISSUE TITLE
There is no active transaction

### ISSUE THREAD

**Issue by perfectminor** [uasoft-indonesia/badaso#609]
**There is no active transaction.**

Hello badaso develover, I'm stepping to create a table on the database management menu. But after selecting save, the table was successfully created because I have seen it in phpmyadmin, but the migrations file was not created automatically, even though it should have been created automatically. If I go to the management database page, the table is successfully displayed. The error message that appears is "There is no active transaction", and this also applies when I delete the table. I've also tried to reinstall badaso but I haven't found this problem resolved. 

**Desktop :**
 - OS: [Windows 7 Pro SP1]
 - Browser [Microsoft Edge Version 99.0.1150.30 (Official build) (64-bit)]
 - PHP Version 8.1.2
 - Node Version 12.22.10
 - Yarn 1.22.4
 - npm 6.14.16
 - Composer 2.1.14
 - Laravel 8
 - Badaso V 2.4.7

**Log Viewer :**

Stack trace:
#0 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(279): PDO->rollBack()
#1 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(254): Illuminate\Database\Connection->performRollBack(0)
#2 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(442): Illuminate\Database\Connection->rollBack()
#3 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Database\DatabaseManager->__call('rollBack', Array)
#4 C:\xampp\htdocs\badasoapps\database\migrations\badaso\2022_03_08_014448_drop_tagsregulations_table_pnwl.php(23): Illuminate\Support\Facades\Facade::__callStatic('rollBack', Array)
#5 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(472): DropTagsregulationsTablePnwl->up()
#6 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(394): Illuminate\Database\Migrations\Migrator->runMethod(Object(Larapack\DoctrineSupport\Connections\MySqlConnection), Object(DropTagsregulationsTablePnwl), 'up')
#7 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(403): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#8 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(202): Illuminate\Database\Migrations\Migrator->runMigration(Object(DropTagsregulationsTablePnwl), 'up')
#9 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(167): Illuminate\Database\Migrations\Migrator->runUp('C:\\xampp\\htdocs...', 2, false)
#10 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(112): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#11 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(85): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#12 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(606): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
#13 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\MigrateCommand.php(94): Illuminate\Database\Migrations\Migrator->usingConnection(NULL, Object(Closure))
#14 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
#15 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Container\Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#17 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call(Array)
#20 C:\xampp\htdocs\badasoapps\vendor\symfony\console\Command\Command.php(298): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#21 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#22 C:\xampp\htdocs\badasoapps\vendor\symfony\console\Application.php(1015): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#23 C:\xampp\htdocs\badasoapps\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#24 C:\xampp\htdocs\badasoapps\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#25 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Console\Application.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#26 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Console\Application.php(186): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#27 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(263): Illuminate\Console\Application->call('migrate', Array, NULL)
#28 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Foundation\Console\Kernel->call('migrate', Array)
#29 C:\xampp\htdocs\badasoapps\vendor\badaso\core\src\Controllers\BadasoDatabaseController.php(219): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#30 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Uasoft\Badaso\Controllers\BadasoDatabaseController->delete(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('delete', Array)
#32 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Uasoft\Badaso\Controllers\BadasoDatabaseController), 'delete')
#33 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#34 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Router.php(721): Illuminate\Routing\Route->run()
#35 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\badasoapps\vendor\badaso\core\src\Middleware\BadasoCheckPermissions.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Uasoft\Badaso\Middleware\BadasoCheckPermissions->handle(Object(Illuminate\Http\Request), Object(Closure), 'delete_database')
#38 C:\xampp\htdocs\badasoapps\vendor\badaso\core\src\Middleware\ApiRequest.php(70): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Uasoft\Badaso\Middleware\ApiRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Router.php(723): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Router.php(698): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Router.php(662): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Routing\Router.php(651): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#46 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 C:\xampp\htdocs\badasoapps\vendor\fruitcake\laravel-cors\src\HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\xampp\htdocs\badasoapps\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 C:\xampp\htdocs\badasoapps\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 C:\xampp\htdocs\badasoapps\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 C:\xampp\htdocs\badasoapps\server.php(21): require_once('C:\\xampp\\htdocs...')
#66 {main}

**Comment by perfectminor** [comment]
Please let us know if the issue is resolved, because I want to try it again. Thank you for the response.

**Comment by perfectminor** [comment]
> This issue already detected in https://github.com/uasoft-indonesia/badaso-starter
> 
> We will fix it tommorow
> 
> For now, you can install badaso manually in laravel, just a small step for that.
> 
> https://badaso-docs.uatech.co.id/getting-started/installation#on-existing-project
> 
> Thank you

Please let us know if the issue is resolved, because I want to try it again. Thank you for the response.

**Comment by perfectminor** [comment]
This issue was resolved in Badaso version 2.4.8. Thank You
